### ISSUE TITLE
pppwn.exe can't run on windows7.

### ISSUE THREAD

**Issue by edison7719** [xfangfang/PPPwn_cpp#11]
pppwn.exe can't run on windows7.
No errors were reported during operation, Are additional dependencies required?
The system has installed npcap normally.

Thanks

**Comment by PSGO** [comment]
应该是缺少C++库，建议安装一个合集

**Comment by xfangfang** [comment]
@edison7719 @superantar

The issue has been solved, you can download again to test.

For details, refer to the following: https://github.com/xfangfang/PPPwn_cpp/pull/13

**Comment by edison7719** [comment]
Hi @xfangfang 
I'll retest it later.

Thanks.

**Comment by edison7719** [comment]
Hi @xfangfang 
The isssue has been solved.
Can by close this issue.

Thanks
