### ISSUE TITLE
Failed to set direction for capturing packets 

### ISSUE THREAD

**Issue by DJTOMATO** [xfangfang/PPPwn_cpp#16]
[ERROR: \build\_deps\pcapplusplus-src\Pcap++\src\PcapLiveDevice.cpp: doOpen:286] Failed to set direction for capturing packets, error code: '-1', error message: 'Setting direction is not supported on this device'
[ERROR: \build\_deps\pcapplusplus-src\Pcap++\src\PcapLiveDevice.cpp: doOpen:286] Failed to set direction for capturing packets, error code: '-1', error message: 'Setting direction is not supported on this device'

Both with network pci card and usb card, windows, using npcap 1.79

**Comment by paulloeduardo** [comment]
i have

[ERROR: /home/runner/work/PPPwn_cpp/PPPwn_cpp/build/_deps/pcapplusplus-src/Pcap++/src/PcapLiveDevice.cpp: doOpen:286] Failed to set direction for capturing packets, error code: '-1', error message: 'Setting direction is not supported on this device'
[ERROR: /home/runner/work/PPPwn_cpp/PPPwn_cpp/build/_deps/pcapplusplus-src/Pcap++/src/PcapLiveDevice.cpp: doOpen:286] Failed to set direction for capturing packets, error code: '-1', error message: 'Setting direction is not supported on this device'

**Comment by xfangfang** [comment]
Having updated the code.

npcap does not support the direction filter of packets, however, this will not result in any issues. Ideally, this configuration should have been removed during the build for Windows, but a minor oversight on my part led to this option remaining enabled under Windows.
