### ISSUE TITLE
100% cpu on wait

### ISSUE THREAD

**Issue by stooged** [xfangfang/PPPwn_cpp#19]
just letting you know an issue that was posted to me.
on the raspberry pi the cpu hits 100% while waiting.

this is the issue posted

https://github.com/stooged/PI-Pwn/issues/33

pppwn64 is a aarch64 compile of PPPwn_cpp

i compiled it with the following options
> -DCMAKE_BUILD_TYPE=MinSizeRel -DZIG_TARGET=aarch64-linux-musl -DUSE_SYSTEM_PCAP=OFF

**Comment by xfangfang** [comment]
@stooged The code is updated.

Setting the waiting timeout to 1ms. Prior to this, pcap defaulted not to wait, causing continuous looping and affecting CPU usage.

**Comment by stooged** [comment]
nice, i will run some tests.

**Comment by stooged** [comment]
the change on
https://github.com/xfangfang/PPPwn_cpp/commit/5f84fbd163ea321602f1bd439768ceb9412d2303

solved the issue on the pi, thankyou

**Comment by piterq** [comment]
@xfangfang
stooged has extended timeouts to 100ms in commit [0b95b2b](https://github.com/stooged/PPPwn_cpp/commit/0b95b2b1b01fa8d363741c71e0bb3c5bdc909dbc)

**Comment by xfangfang** [comment]
@piterq I feel that for modern CPUs, there won't be much difference between 100ms and 1ms

**Comment by stooged** [comment]
@piterq the fork i have is specifically for pi-pwn and the raspberry pi, the change was only because i was getting inconsistent results on older pi models.

the changes on my fork are not really for this repo.
