### ISSUE TITLE
在openwrt路由上如何一步一步操作

### ISSUE THREAD

**Issue by ytalm** [xfangfang/PPPwn_cpp#22]
请教openwrt路由安装好PPPOE服务器插件后，请问下一步路由里再需要注入什么，以实现PPPwn运行

**Comment by xfangfang** [comment]
@ytalm 您好，我不知道这里的 “PPPOE服务器插件” 指的具体是什么(server 还是 client)，如果你要在 openwrt 上运行一个 PPPoE server 的话，这是不推荐的，因为PPPwn就是伪装成一个 PPPoE server，安装其他的 server会导致数据可能发不到 PPPwn。

正常来说在 openwrt里的使用方法和其他平台下没有任何区别，把openwrt当作一台linux PC使用就可以了。

**Comment by ytalm** [comment]
https://github.com/FalsePhilosopher/PPPwnWRT
