### ISSUE TITLE
fails to cross-build/compile for Windows

### ISSUE THREAD

**Issue by EatThisRock** [xfangfang/PPPwn_cpp#23]
When running 
`cmake --build build -t pppwn`

I get:

> [  0%] Building CXX object _deps/pcapplusplus-build/Common++/CMakeFiles/Common++.dir/src/GeneralUtils.cpp.obj
> In file included from <built-in>:434:
> <command line>:10:9: error: macro name must be an identifier
>    10 | #define -D_Post_invalid_
>       |         ^
> 1 error generated.
> gmake[3]: *** [_deps/pcapplusplus-build/Common++/CMakeFiles/Common++.dir/build.make:77: _deps/pcapplusplus-build/Common++/CMakeFiles/Common++.dir/src/GeneralUtils.cpp.obj] Error 1
> gmake[2]: *** [CMakeFiles/Makefile2:1031: _deps/pcapplusplus-build/Common++/CMakeFiles/Common++.dir/all] Error 2
> gmake[1]: *** [CMakeFiles/Makefile2:402: CMakeFiles/pppwn.dir/rule] Error 2
> gmake: *** [Makefile:182: pppwn] Error 2

Can't seem to find a reason for it?

I am using Ubuntu WSL on Windows 10.

Using Ubuntu WSL, I can compile/build the linux binary and runs just fine.

**Comment by EatThisRock** [comment]
If you mean before compiling, I used:
`cmake -B build -DZIG_TARGET=x86_64-windows-gnu -DUSE_SYSTEM_PCAP=OFF -DPacket_ROOT=/mnt/c/Users/USERNAME/Desktop/PS4/npcap_win_sdk`

**Comment by xfangfang** [comment]
1. is the version of npcap SDK 1.13?
2. If the `build` directory was previously used to compile with different cmake option, please delete it and try again
3. Using MSYS2 mingw32/64 to do a native compile
4. Using a real linux or mac to cross compile

You can check the workflow for more information (both `mingw` and `cross compile from linux` are contained )

https://github.com/xfangfang/PPPwn_cpp/blob/main/.github/workflows/ci.yaml

**Comment by EatThisRock** [comment]
Thanks, I've done 1-2 before. But 3 seems like a good suggestion.

**Comment by EatThisRock** [comment]
After spending more time into it and given mingw64 was failing elsewhere with no solution in sight, I was able to fix it by adding 

```
#ifndef _Post_invalid_ 
#define _Post_invalid_    
#endif
```

to `Packet32.h` from npcap sdk/include folder. 

and commented out `add_compile_definitions(-D_Post_invalid_=)` on CMakeLists.txt, it was able to compile just fine with WSL Ubuntu on Windows 10.

After having npcap installed in windows the compiled binary runs with better success rate than vanilla PPPwn

I am not sure if is the 'right' solution, but is a workaround if anyone is interested.

[sauce](https://github.com/the-tcpdump-group/libpcap/issues/1118)

**Comment by EatThisRock** [comment]
> if cmake >= 3.26 it will remove the leading `-D` in `add_compile_definitions(-D_Post_invalid_=)`.
> 
> So I guess the issue was caused by the cmake version. I just submitted an update, and now it should be possible to compile without modifying the npcap SDK.
> 
> [f5940c3](https://github.com/xfangfang/PPPwn_cpp/commit/f5940c39a1ec5dbd7a986cffd706932727f1f7fd)

Neato, definitely is a better option. Thank you

**Comment by oresterosso75** [comment]
yet the path is correct!
why do I get this error?

`-- Could NOT find Packet (missing: Packet_LIBRARY Packet_INCLUDE_DIR)
CMake Error at build/_deps/pcapplusplus-src/CMakeLists.txt:127 (message):
  Please specify Packet library -DPacket_ROOT=<NPCAP_SDK_PATH>


-- Configuring incomplete, errors occurred!`

**Comment by xfangfang** [comment]
@oresterosso75 

You need to provide the environment and cmake command. while referring to the workflow mentioned earlier.

In Linux, you need to pay attention to the issue of path capitalization (which is why workflow modified the path of sdk). The cmake option set for compiling using mingw and cross-compiling in Linux are different (-DPACP_ROOT /-DPacket_ROOT)

**Comment by oresterosso75** [comment]
> @oresterosso75
> 
> È necessario fornire l'ambiente e il comando cmake. facendo riferimento al flusso di lavoro menzionato in precedenza.
> 
> In Linux, è necessario prestare attenzione al problema della capitalizzazione del percorso (motivo per cui il flusso di lavoro ha modificato il percorso dell'SDK). L'opzione cmake impostata per la compilazione utilizzando mingw e la compilazione incrociata in Linux è diversa (-DPACP_ROOT /-DPacket_ROOT)

Never before have I found myself in difficulty like today, I have truly tried everything.
I'm forced to give up

**Comment by xfangfang** [comment]
@oresterosso75 Providing an error message cannot solve any problem. You need to show what you have done so that others can help you.

example: I am trying to cross compile to Windows under Ubuntu 22.04, using `cmake -DPacket_ROOT=...` Afterwards, an error occurred, and here is the path to npcap sdk: `tree sdk` ....

You really need to learn this article: http://catb.org/~esr/faqs/smart-questions.html

**Comment by xfangfang** [comment]
@oresterosso75 As mentioned earlier, either use [mingw32/64](https://www.msys2.org) for native compilation or cross compile with Linux(macOS, WSL...)

These two compilation methods have been confirmed, you can refer to the [workflow](https://github.com/xfangfang/PPPwn_cpp/blob/main/.github/workflows/ci.yaml).

I haven't tried running cmake directly in CMD for compilation, but it should be a little complex and require manual handling of dependency issues.

Maybe you can try changing the SDK path to: `\C:\PPPwn_cpp-main\npcap-sdk` or `/C:\PPPwn_cpp-main\npcap-sdk`
