### ISSUE TITLE
unable to run on mips router (not urgent)

### ISSUE THREAD

**Issue by SLAzurin** [xfangfang/PPPwn_cpp#24]
Hello!

This is not urgent because I have a spare raspberry pi but I am curious to see if you understand the issue here for my router.

My router is a ASUS router with the `mips` cpu arch.

![image](https://github.com/xfangfang/PPPwn_cpp/assets/69220163/96242aee-0670-41ab-8610-9f6677991fe8)

I am using `mipsel-linux-musl` from commit `5f84fbd163ea321602f1bd439768ceb9412d2303`.

**Comment by SLAzurin** [comment]
If this use case is not valid, please feel free to close this issue.

**Comment by xfangfang** [comment]
@SLAzurin You can't use `any` for interface, `any` is for capture traffic, but we also need to send packet.

**Comment by SLAzurin** [comment]
@xfangfang Issue resolved after changing iface to eth0
