### ISSUE TITLE
Working on Enigma2 based Satellite boxes. (tested on vu+ uno 4k se)

### ISSUE THREAD

**Issue by mrdude2478** [xfangfang/PPPwn_cpp#26]
FYI incase you want to know, this has now been tested on a VU+ uno 4k se set top box, it was plugged in next to my TV (and PS4) so I thought I would test it out. As expected it runs just fine and picks up the network interfaces.

![Proof](https://i.imgur.com/8S5Zbvo.png)

Now I just need to make a plugin, which is pretty easy to do. Thanks for posting, I know this is not an error but I thought you should know it works just fine. I also tested on a Synology NAS and that worked good as well.

**Comment by edisionnano** [comment]
Using OpenVix to jailbreak a PS4, this put a smile to my face.
