### ISSUE TITLE
Use the PPPoE username or password to determine the system version

### ISSUE THREAD

**Issue by pi-three** [xfangfang/PPPwn_cpp#29]
Hi, very grateful for your work on this.

Is it possibe to add feature as described in [TheOfficialFloW/PPPwn pull request #56?](https://github.com/TheOfficialFloW/PPPwn/pull/56)

Thanks again,
pithree.

**Comment by Doyle4** [comment]
No need as you only use the files for your firmware.

**Comment by pi-three** [comment]
Hi, thank you for your response.

I believe it will be beneficial for pepople with multiple systems with different firmware like me, I have 9.00 for main, 11.00 for testing and other low firmwares.
If it could be setup one time with only one pi, for example, using [Pl-Pwn](https://github.com/stooged/PI-Pwn) without have to mess with the script everytime to use it with different firmware it will be a lifesaver.

**Comment by pi-three** [comment]
Hi, thanks for the heads up on that.

I'll definitely look into that and see if it fit my use case,
but fingers crossed i'm still hoping this get implemented though,
just for the less techie person or kids.

**Comment by xfangfang** [comment]
@pi-three I have added web page management in the latest build. You can use different ports to host multiple services.

https://nightly.link/xfangfang/PPPwn_cpp/workflows/ci.yaml/main?status=completed

**Comment by pi-three** [comment]
@xfangfang Thank you for taking the time to work on this project of yours.
I hope you keep improving this project to be easier to use & find ways to increase the pwned rate.

I'll check the new web page management.
