### ISSUE TITLE
能否在docker中运行呢？

### ISSUE THREAD

**Issue by BlueFKiller** [xfangfang/PPPwn_cpp#31]
PPPwn_cpp能不能在群晖Docker中运行呢？

**Comment by xfangfang** [comment]
@BlueFKiller 不太清楚群晖具体都有什么功能，如果可以直接运行可执行文件的话，不知道为什么需要用docker来运行。

如果实在是想用docker来执行，那么简单写个Dockerfile就行，需要注意的是运行时应该有权限限制，如何运行可以参考：https://github.com/travelping/docker-pcap
