### ISSUE TITLE
stuck on waiting for PADR 

### ISSUE THREAD

**Issue by lamineovich** [xfangfang/PPPwn_cpp#33]
hello, when trying to jb my ps4, im getting stuck on waiting for PADR on the pppwn loader and i get fail to obtain ip adress on the ps4

**Comment by xfangfang** [comment]
https://github.com/xfangfang/PPPwn_cpp/issues/18#issuecomment-2109368948

**Comment by lamineovich** [comment]
hi thank you for youer response and your work, i have read the comment and frankly they are above my understanding, not sure if they include a solution, some info here: id do have npcap installed and my ps4 is directly connectrd to my pc, i tried 3 diffrenent computer and still getting the same problem

**Comment by xfangfang** [comment]
If you have already connected PS4 directly to the PC but still get stuck in PADR, it means something is blocking pppwn from receiving packet from PS4.

Maybe you can check the firewall?

If it really cannot be solved, you can use Wireshark to monitor the interface traffic after pppwn_cpp is turned on. After PS4 shows that the IP address cannot be obtained, save it as PCAP and upload it here.

**Comment by lamineovich** [comment]
update: i managed to get it work with a computer which have an qualcomm atheros pcie card ( and it was from the first try)
while when using my laptop with ethernet adapter it doesnt work same with a laptop with realteck card

**Comment by lamineovich** [comment]
update 2: i managed to get it works with the ethernet adapter on my laptop simply by installing the latest driver for the adapter
thank you for your time

**Comment by xfangfang** [comment]
> Possible causes could be that the PS4 is not directly connected to the device, or the failure in setting the network card's promiscuous mode (although this is quite unlikely).

Perhaps due to driver issue, we are unable to set the network card to promiscuous mode, resulting in the inability to receive packet. That's a good point, I will update the readme or the wiki, Thanks for your feedback.

**Comment by dreamGz** [comment]
> Actualización: logré que funcionara con una computadora que tiene una tarjeta PCIe Qualcomm Atheros (y fue desde el primer intento), mientras que cuando uso mi computadora portátil con un adaptador Ethernet no funciona, lo mismo ocurre con una computadora portátil con una tarjeta Realteck.



> Actualización 2: logré que funcione con el adaptador Ethernet en mi computadora portátil simplemente instalando el último controlador para el adaptador, gracias por su tiempo.

Como se llama el controlador para el adaptador?? Te necesito... Xc
