### ISSUE TITLE
I can't compile raspberry 4 - aarch64

### ISSUE THREAD

**Issue by vincelory** [xfangfang/PPPwn_cpp#36]
Why i can't compile ? 

"
cmake -B build -DZIG_TARGET=arm-linux-musleabi -DUSE_SYSTEM_PCAP=OFF -DZIG_COMPILE_OPTION="-mcpu=cortex_a7"
-- ZIG_TARGET: arm-linux-musleabi
-- OS: Linux
-- ARCH: arm
-- Custom compile options: -mcpu=cortex_a7
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:43 (project):
  The CMAKE_C_COMPILER:

    /home/raspy/ps4/PPPwn_cpp-main/build/vendor/zig-tools/zig-cc.sh;-target;arm-linux-musleabi

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:43 (project):
  The CMAKE_CXX_COMPILER:

    /home/raspy/ps4/PPPwn_cpp-main/build/vendor/zig-tools/zig-cpp.sh;-target;arm-linux-musleabi

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path  to the compiler, or to the compiler name if it is in the PATH."

**Comment by Andryshik345** [comment]
> -- ZIG_TARGET: arm-linux-musleabi
This target for old RPi boards with armv7 arch.
> -- Custom compile options: -mcpu=cortex_a7
This option is also not needed.

Just pass:
```
cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel -DUSE_SYSTEM_PCAP=OFF
cmake --build build -t pppwn -j$(nproc)
```
and it should compile.

**Comment by vincelory** [comment]
Yes i resolve it!! But now i cant execute pppwn 🫠

**Comment by Doyle4** [comment]
Use https://github.com/stooged/PI-Pwn its built around xfangfang code.
