### ISSUE TITLE
PPPwn "Killed" Linksys E1200

### ISSUE THREAD

**Issue by tongduanmingo** [xfangfang/PPPwn_cpp#42]
![image](https://github.com/xfangfang/PPPwn_cpp/assets/78008112/cd6862b8-7950-4239-a68c-221cf7d9add7)
is it router not supporting or binary fault ?

**Comment by tongduanmingo** [comment]
what can be the problem less ram ?
mips binary
there was 10 MB free temp disk i tried to use it too still 
mount tmpfs /tmp -t tmpfs -o remount,size=11000k,nosuid,nodev

**Comment by xfangfang** [comment]
I don't know either. You can compile from the source code and add more logs to see where the problem occurred

**Comment by stanleyws** [comment]
Probably caused by low ram. On my ac87u it takes about 19MB free ram to run pppwn:

```
Mem: 66524K used, 189152K free, 5792K shrd, 496K buff, 10824K cached
CPU:  0.0% usr  0.7% sys  0.0% nic 98.2% idle  0.0% io  0.0% irq  0.9% sirq
Load average: 0.07 0.03 0.05 1/75 1309
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 1281  1280 admin    S     9192  3.5   0  0.9 ./pppwn --interface br0 --fw 1100 --stage1 stage1_1100.bin --stage2 stage2_11.00.bin -a
 1280  1279 admin    S     9200  3.5   0  0.5 ./pppwn --interface br0 --fw 1100 --stage1 stage1_1100.bin --stage2 stage2_11.00.bin -a
```

Your router only has 32MB ram in total and 6MB free ram when running. I'd try to connect a usb drive and set up swap file/partition, or get another router with more ram

**Comment by tongduanmingo** [comment]
@stanleyws yeah i was doubtfull about its because of ram you just confirmed it, do you know any idea whats the required ram for pppwn ? so i will go with the cheapest router 
will it work on 8MB Flash & 64MB RAM

**Comment by xfangfang** [comment]
Added an option to specify the buffer size for PCAP: --buffer-size

I tested that setting it to 10240 can run normally, and the memory usage is about 3MB.

For specific instructions, please refer to the readme of the dev branch: https://github.com/xfangfang/PPPwn_cpp/tree/dev

Download: https://github.com/xfangfang/PPPwn_cpp/actions/runs/9199126592

---

```shell
ps -aux | grep pppwn

root     30237  1.1  0.5  11228  2772 pts/0    Sl+  21:58   0:00 ./pppwn --interface lan1 --stage1 stage1.bin --stage2 stage2_9.00.bin --fw 900 -t 10 -wap 1 -gd 4 -a -nw -bs 10240
```
---

By the way, VSZ (Virtual Set Size) is not a true memory usage, even a blank std:: thread can cause VSZ to increase by 8MB. RSS (Resident Set Size) is the real one.

VSZ: 11228 KB
RSS: 2772 KB

**Comment by tongduanmingo** [comment]
Finally its works great thanks bro --buffer-size is best feature
