### ISSUE TITLE
-wait-after-pin only works on first run, further attempts do not cause delay

### ISSUE THREAD

**Issue by winchesterpro5** [xfangfang/PPPwn_cpp#51]
-wait-after-pin only works on the first launch, further attempts do not cause a delay, is this how it should be?

**Comment by xfangfang** [comment]
`--wait-after-pin`: the waiting time in seconds after **first round** CPU pinning (default: 1)

The main purpose of placing this option is to avoid crashes caused by opening pppwn before PS4 starts, as running pppwn too early may cause PS4 to crash.
