### ISSUE TITLE
2015 intel macbook pro issue

### ISSUE THREAD

**Issue by bajinmuu2** [xfangfang/PPPwn_cpp#54]
Hi everyone,

I;m getting 

Chris$ /Users/Chris/Desktop/PPPwn/pppwn —interface en5 --fw 1100 --stage1 /Users/Chris/Desktop/PPPwn/stage1.bin --stage2 /Users/Chris/Desktop/PPPwn/stage2.bin --auto-retry
-bash: /Users/Chris/Desktop/PPPwn/pppwn: Bad CPU type in executable

I've also tried using the x86 macOS from nightly but that doesnt work either

**Comment by xfangfang** [comment]
I saw in another issue that you successfully executed it.

There are now two versions, x86-64 and aarch64. You should use x86-64 and ensure that the system is above macos11. If the system version is too old, you need to compile this application yourself
