### ISSUE TITLE
USB以太网转换器无法被识别？

### ISSUE THREAD

**Issue by LittleFIve233** [xfangfang/PPPwn_cpp#6]
![image](https://github.com/xfangfang/PPPwn_cpp/assets/68946023/c8c0a0b0-b20c-4ef5-8c66-6943483ec1f4)
如题，list中有对应的设备，但是当使用时则无法被识别

**Comment by Andryshik345** [comment]
Try `--interface "\Device\NPF_{A499E3B3-160D-40EA-9A8C-E04F71951B09}"` instead.

**Comment by xfangfang** [comment]
@LittleFIve233 前面的是网卡ID，后面的对应的描述，按前面评论中说的内容来使用就好啦～

先关闭这个issue了
