### ISSUE TITLE
pppwn.exe, pack.exe (Clarifications)

### ISSUE THREAD

**Issue by oresterosso75** [xfangfang/PPPwn_cpp#60]
After the previous compilation compared to the one carried out this evening I noticed that a new "pack.exe" file was added.
So now I also have this along with PPPwn.exe.
I guess they have to be together in order to communicate.
I also assume that the absence of 
this new "pack.exe" would not allow correct functioning.
question, is it essential?
Specifically, what is it for and how is it used?
Thank you

**Comment by xfangfang** [comment]
https://github.com/xfangfang/PPPwn_cpp/blob/ae5c32461070d5e358724865e863ff0e96122146/CMakeLists.txt#L130-L136
