### ISSUE TITLE
[Feature req] Route traffic after successfull jailbreak

### ISSUE THREAD

**Issue by Gouster4** [xfangfang/PPPwn_cpp#65]
Hello. Its not bad idea to run PPPwn on router, as its online 24/7.
But after jailbreak, we need to disable PPPoE client (which breaks automatized jailbreaking), or manually run PPPoE server.

Is it possible to embedd PPPoE server into PPPwn_cpp, so with some pppwn parameter, it will host PPPoE server for internet access on jailbroken PS4?

Also, if PPPoE client (PS4) disconnects, it can start jailbraking over again? this way once PS4 has PPPoE client enabled, jailbreak will be fully automatic.

**Comment by xfangfang** [comment]
maybe you can try ：https://github.com/stooged/PI-Pwn

they run pppoe-server after jailbreak.

I have implemented a simple version of pppoe server for macOS and Windows, but it does not work on Linux.

https://github.com/xfangfang/PPPwn_cpp/tree/gateway

I haven't tried it before, but maybe you can make it work under Linux by adding this modification：https://stackoverflow.com/a/8578541

**Comment by Gouster4** [comment]
Thank you. I didn't noticed gateway branch. This sounds very promising. I will try it on my Linux PC, and also on OPNSense (FreeBSD), and share results.

**Comment by Gouster4** [comment]
I got this error when triyng to compile.
But main branch does compile without any problems.
Do i have some libraries missing?

[ 87%] Building CXX object CMakeFiles/pppwn_static.dir/src/gateway.cpp.o
/root/PPPwn_cpp/src/gateway.cpp:62:24: error: variable has incomplete type 'struct sockaddr_in'
    struct sockaddr_in addr{};
                       ^
/root/PPPwn_cpp/src/gateway.cpp:62:12: note: forward declaration of 'sockaddr_in'
    struct sockaddr_in addr{};
           ^
/root/PPPwn_cpp/src/gateway.cpp:64:34: error: use of undeclared identifier 'INADDR_ANY'
    addr.sin_addr.s_addr = htonl(INADDR_ANY);
                                 ^
2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /root/PPPwn_cpp
*** Error code 1

Stop.
make[1]: stopped in /root/PPPwn_cpp
*** Error code 1

Stop.
make: stopped in /root/PPPwn_cpp

**Comment by Gouster4** [comment]
https://github.com/xfangfang/PPPwn_cpp/pull/67
Found out source of issue, and solution.
So, i created pull request.

**Comment by Gouster4** [comment]
So, i managed to start gateway on OPNSense with INADDR_ANY fix from my PR.
But i didnt got internet access on it, as fix uses iptables command which isnt present on FreeBSD, so an alternative for it is needed. Will try to find one.

But, after i powered off my PS4, gateway was still running. Is there any way to automatically stop it after cient (ps4) disconnects?
Same way as PPPwn closes itself after sucessfull jaibreak.
So i can automatically run PPPwn again waiting for PS4 after an reboot/power cycle.

Thank you.

**Comment by xfangfang** [comment]
The problem may occur in different places on freebsd, which requires checking the pcap traffic on the router to determine the specific problem.

I think the best alternative is to use a real pppoe-server, which can better match the operating system. The current gateway branch is just a simple platform independent implementation, which is inefficient and may have packet loss or performance issues.

Perhaps an elegant approach is you can write a simple web service that calls pppwn and pppoe-server, in which case you can freely combine the desired operations

**Comment by Gouster4** [comment]
I tried clean FreeBSD and also OPNSense. 
Ended up using mpd5 as PPPoE server.
Got IP assigned, but no internet access.
But it's just matter of tweaking mpd5 config.
