### ISSUE TITLE
PPPwn_cpp & windows 7

### ISSUE THREAD

**Issue by superantar** [xfangfang/PPPwn_cpp#7]
first thank you for your work.
I tried PPPw_cpp under Windows 7 sp1 and it doesn't work
no error, no output, just exit

**Comment by xfangfang** [comment]
@superantar is your system x86 or x86_64 ?

**Comment by superantar** [comment]
is x86_64

**Comment by xfangfang** [comment]
You need to install [npcap](https://npcap.com) before run this program.

If you have already installed it, then I don't know either.

**Comment by superantar** [comment]
> You need to install [npcap](https://npcap.com) before run this program.
Yes, I installed it before testing.

      No problem, thank you for your quick answer :)
