### ISSUE TITLE
Stuck on [+] STAGE 2: KASLR defeat (PS4 slim crashes) Im going crazy...

### ISSUE THREAD

**Issue by Jordifv15** [xfangfang/PPPwn_cpp#83]
Just bought a new PS4 slim CUH-2216A. Im using mac os and using the guide https://github.com/xfangfang/PPPwn_cpp/issues/10

Everything goes lovely until it constantly crashes just before finding the corruption filed of STAGE 1. Than when I turn on the PS4 again, it shows [+] STAGE 2: KASLR defeat but it stays there.

I'm using the latest version of PPPwn for mac os intel based and I've tried multiple Stage 1 and Stage 2 files (note: I haven't been able to finde the Stage 1.bin file updated with corrections from mid june). I dont know what else to do and Im going crazy. 

If someone could help me I would be forever grateful

**Comment by DrYenyen** [comment]
Hi there if you'd like you can message me on Discord at Dr.Yenyen i can offer some advice and we can try to troubleshoot together.

**Comment by Jordifv15** [comment]
Thank you, I've been able to solve it by myself. If anyone is interested what I did was simply:

1- Download the first release of pppwn c++ from this link: https://github.com/xfangfang/PPPwn_cpp/releases/tag/1.0.0. Somehow, the latest version makes my ps4 kernel panic all the time. but wit this version it runs smooth.
2- Use the stage1.bin and stage2.bin from here: https://github.com/0x1iii1ii/PPPwn-Luckfox

Using those files I've been able to inject the payload close to 50 times with only 2 or 3 times of "freezing" during the process.

So very happy and relieved :)

**Comment by LouisGarry** [comment]
> Thank you, I've been able to solve it by myself. If anyone is interested about what I did, it was simply:
> 
> 1- Download the first release of pppwn c++ from this link: https://github.com/xfangfang/PPPwn_cpp/releases/tag/1.0.0. Somehow, the latest version makes my ps4 kernel panic all the time. But with this version it runs smooth almost always.
> 
Hi @Jordifv15 , are you using the arm-linux-musleabi.cortex_a7.zip? I want to try.
Thanks.
