### ISSUE TITLE
Request for RISC V build/support  ?

### ISSUE THREAD

**Issue by NoSwear** [xfangfang/PPPwn_cpp#88]
Hi, is there any possibility to add Support For " RISC v " architecture

**Comment by xfangfang** [comment]
https://github.com/xfangfang/PPPwn_cpp?tab=readme-ov-file#development

Adding `-DZIG_TARGET=riscv64-linux-musl` to build command, and you can build for riscv64.

Considering `memory alignment` issues ( https://github.com/xfangfang/PPPwn_cpp/issues/34 ), I'm not sure if this will work properly.

test build from my local machine:
[pppwn-riscv64-linux-musl.zip](https://github.com/user-attachments/files/16736199/pppwn-riscv64-linux-musl.zip)

**Comment by NoSwear** [comment]
![Capture d’écran (1201)](https://github.com/user-attachments/assets/8e3ee681-0885-4953-97df-cbf9833eef5f)
Thank you it works !

**Comment by NoSwear** [comment]
and one more question pls, is this based on pppwn normal one or the pppwn_ipv6 ? because some console refuse to work with the normal one always crashes some console never succeed to make it run. thank you !

**Comment by xfangfang** [comment]
The test build above should be the `normal one`. I have been wanting to add a switching function to let users decide which IPv6 address to use, but I haven't had time to wirte it yet.

**Comment by NoSwear** [comment]
ah ok , thanks for the time and effort !
