### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by NoSwear** [xfangfang/PPPwn_cpp#89]
hello, is there a way to reduce memory usage ? the app consume about 9.5 mb ram total .and i have pocket router that has only 16 mb (i managed to get only 4 , 5 mb max free memory. 32 mb routers runs fine .

**Comment by xfangfang** [comment]
see the readme:  `--buffer-size 10240` 

Perhaps you can use a smaller value, I'm not sure what the minimum should be.

**Comment by NoSwear** [comment]
thank you i found the same in https://github.com/xfangfang/PPPwn_cpp/issues/42 i was testing i'll give you feedback thank you again !

**Comment by NoSwear** [comment]
it Works ! thank you .
