### ISSUE TITLE
Nightly build expired

### ISSUE THREAD

**Issue by Tokarak** [xfangfang/PPPwn_cpp#90]
There are no precompiled binaries on HEAD available — time for a new release?

**Comment by Fareast07** [comment]
I second that, Would be great if the links worked again.

**Comment by FalsePhilosopher** [comment]
I came to see for updates and found the same issue. I have builds pulled from the nightly build link in the pppwnwrt repo if anybody is looking for a source for a precompiled release.

**Comment by xfangfang** [comment]
https://nightly.link/xfangfang/PPPwn_cpp/actions/runs/11035457100

https://github.com/xfangfang/PPPwn_cpp/actions

**Comment by FalsePhilosopher** [comment]
> https://nightly.link/xfangfang/PPPwn_cpp/actions/runs/11035457100
> 
> https://github.com/xfangfang/PPPwn_cpp/actions

Link in the readme still points to outdated artifact builds https://nightly.link/xfangfang/PPPwn_cpp/workflows/ci.yaml/main?status=completed

**Comment by xfangfang** [comment]
https://github.com/xfangfang/PPPwn_cpp/releases/tag/1.1.0
